### ISSUE TITLE
Use OAuth for retrieving API token

### ISSUE THREAD

**Issue by robertknight** [haritzmedina/reviewAndGo#3]
Hello @haritzmedina,

We recently noticed an unexpectedly large number of requests to https://hypothes.is/account/developer which we suspected may be being made by automated tools. After doing some analysis and searching we came across this extension. It is great to see people doing cool things with our API. Scraping that page is not a way to access the API that we can recommend/support however.

If you are trying to use the Hypothesis API from a browser extension, the supported way to do that is using our [OAuth support](https://h.readthedocs.io/en/latest/api/using-oauth/). We use this [in the Hypothesis client](https://github.com/hypothesis/client/blob/master/src/sidebar/util/oauth-client.js) itself.

Unfortunately using OAuth from a Chrome extension is a bit fiddly, but there is documentation out there on how to do this for other services. If you can provide us with a contact Hypothesis username and the extension IDs of any extensions that you want to use with the Hypothesis API, we can provide you with an OAuth client ID to get started.

**Comment by haritzmedina** [comment]
Hi @robertknight,

First of all my apologies for the vast number of requests that we are doing to retrieve the Hypothes.is user token to use your API. As a temporary solution we have already reduced the number of requests to https://hypothes.is/account/developer.

I've been trying to understand and use your Hypothes.is OAuth client implementation and it looks quite straightforward to adapt our current implementation. However, currently, we have 4 different plugins that are using Hypothes.is API and we are planning to generate some others in the near future. I would like to know:
1. How can we provide our Hypothes.is username and extensions IDs to register OAuth clients? I found how to register new OAuth clients in my own instance of hypothesis/h, but I wouldn't be able to find any kind of form in the [documentation](https://h.readthedocs.io/en/latest/api/using-oauth/#registering-an-oauth-client) or in [github](https://github.com/hypothesis/h).
2. If there is not a form to register new clients, are you planning to develop a form where other users can register their own hypothes.is API clients? Something similar to [Mendeley's](https://dev.mendeley.com/myapps.html) or [Google Cloud Platform](https://console.developers.google.com/apis).

Apart from that, @judell told me that it would be useful to provide a shared library which can be re-used easily for OAuth authentication for Hypothes.is (in both browser and server-side node apps), as same as https://github.com/judell/hlib or https://github.com/haritzmedina/hypothesis-api-client. It looks that the implementation in [Hypothes.is client](https://github.com/hypothesis/client/blob/master/src/sidebar/util/oauth-client.js)  is specifically for chrome extensions, or I'm wrong?

**Comment by robertknight** [comment]
Hello @haritzmedina -

Thank-you for the updates to the extension to reduce the number of requests to https://hypothes.is/account/developer. This shouldn't have been a problem but it happened to trigger some inefficient database usage in our backend, which we've since fixed 🙂

> How can we provide our Hypothes.is username and extensions IDs to register OAuth clients?

Currently only Hypothesis staff can do this. Let us know (here, or via the Hypothesis Open Slack channel) your Hypothesis username and the URLs which you want to use to receive the OAuth auth code and we can register clients for you.

> If there is not a form to register new clients, are you planning to develop a form where other users can register their own hypothes.is API clients?

There is a tracking issue for this here: https://github.com/hypothesis/product-backlog/issues/376. We haven't currently scheduled when this will be done, but it seems like an obvious thing to do in principle.

> It looks that the implementation in Hypothes.is client is specifically for chrome extensions, or I'm wrong?

The implementation in the Hypothesis client works for any browser-based JS app, not just browser extensions. It won't work for server-side clients as it uses `Window.postMessage` to communicate the OAuth auth code back to the client after authorization rather than a redirect, which is how OAuth 2 typically works.

Feel free to contact me as well if you need any help implementing an OAuth client.

**Comment by haritzmedina** [comment]
Hi @robertknight,

> Thank-you for the updates to the extension to reduce the number of requests to https://hypothes.is/account/developer. This shouldn't have been a problem but it happened to trigger some inefficient database usage in our backend, which we've since fixed 🙂

Thank you for the explanation, I'm glad the problem is fixed and it is not causing that inefficient usage in the backend.

I've been integrating your OAuth client in our Hypothes.is clients and it seems that it works fine! Now, what we want to do is just to integrate those changes in production. I've followed the idea of Hypothes.is/client, and the origin URLs will be "chrome-extensions://" followed by each of the extensions below:
* [DScaffolding](https://chrome.google.com/webstore/detail/dscaffolding/hkgmnnjalpmapogadekngkgbbgdjlnne?hl=en): chrome-extensions://hkgmnnjalpmapogadekngkgbbgdjlnne
* [Highlight&Go](https://chrome.google.com/webstore/detail/highlightgo/bihmalipgnlomidlpekdnoohiejppfmo?hl=en): chrome-extensions://bihmalipgnlomidlpekdnoohiejppfmo
* [Mark&Go](https://chrome.google.com/webstore/detail/markgo/kjedcndgienemldgjpjjnhjdhfoaocfa?hl=en): chrome-extensions://kjedcndgienemldgjpjjnhjdhfoaocfa
* [Review&Go](https://chrome.google.com/webstore/detail/reviewgo/hgiannlbfceoomjmcgedbmkfeblbcogi): chrome-extensions://hgiannlbfceoomjmcgedbmkfeblbcogi

> Let us know (here, or via the Hypothesis Open Slack channel) your Hypothesis username

And, if it is required, my Hypothes.is username is "[haritzmedina](https://hypothes.is/users/haritzmedina)". Don't hesitate to contact me if you need some extra information.

> It won't work for server-side clients as it uses Window.postMessage to communicate the OAuth auth code back to the client after authorization rather than a redirect, which is how OAuth 2 typically works.

Well, it simplifies a lot the implementation of a shared library for client authentication, but, probably, I will need two different implementations for JS apps, one for node-based applications and another one for browser-side apps.

**Comment by robertknight** [comment]
Hi @haritzmedina - I've registered OAuth clients with the origins you gave above. Here are the OAuth client IDs:

DScaffolding - 9a63814a-7e36-11e9-ac44-0fa8228afeea
Highlight & go - bea89e64-7e36-11e9-a6ab-134f99967cf3
Mark & go - f2905a32-7e36-11e9-bc75-df9de7e811fb
Review & go - 120a1f06-7e37-11e9-bbe0-c3e92559eab1
